version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: httpd:latest
    ports:
      - "8080:80"

  db:
    image: postgres:14
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: mydb
    ports:
      - "3306:3306"
